name: Build Windows Bot API

on:
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          choco install openssl -y
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y

      - name: Configure
        run: cmake -A x64 -DCMAKE_BUILD_TYPE=Release .

      - name: Build
        run: cmake --build . --config Release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: telegram-bot-api-windows
          path: |
            Release/telegram-bot-api.exe
            Release/*.dll
